DbShop/Controllers/BannerImagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbShop.BLL.Contracts;
using DbShop.Models.EntityModel;
using DbShop.ViewModel;

namespace DbShop.Controllers
{
    public class BannerImagesController : Controller
    {
        public IBannerImageManager BannerImageManager;

        public BannerImagesController(IBannerImageManager Manager)
        {
            BannerImageManager = Manager;
        }
        // GET: SliderImage
        public ActionResult Index()
        {
            var bannerImage = BannerImageManager.GetAll();
            List<BannerImageViewModel> bannerImageViewModels = new List<BannerImageViewModel>();
            foreach (var data in bannerImage)
            {
                bannerImageViewModels.Add(new BannerImageViewModel()
                {
                    Id = data.Id,
                    Title = data.Title,
                    Discount = data.Discount,
                    ImagePath = data.ImagePath
                });
            }
            return View(bannerImageViewModels);
        }

        // GET: BannerImage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bannerImage = BannerImageManager.GetById((int)id);
            BannerImageViewModel bannerImageViewModel = new BannerImageViewModel()
            {
                Id = bannerImage.Id,
                Title = bannerImage.Title,
                Discount = bannerImage.Discount,
                ImagePath = bannerImage.ImagePath
            };
            return View(bannerImageViewModel);
        }

        // GET: BannerImage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BannerImage/Create
        [HttpPost]
        public ActionResult Create(BannerImageViewModel bannerImageViewModel)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(bannerImageViewModel.Image.FileName);
                string extension = Path.GetExtension(bannerImageViewModel.Image.FileName);
                var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                fileName = Path.Combine(Server.MapPath("~/BannerImage/"), fileNames);
                bannerImageViewModel.Image.SaveAs(fileName);

                BannerImage bannerImage = new BannerImage()
                {
                    Title = bannerImageViewModel.Title,
                    Discount = bannerImageViewModel.Discount,
                    ImagePath = path,
                };
                BannerImageManager.Add(bannerImage);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BannerImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bannerImage = BannerImageManager.GetById((int)id);
            BannerImageViewModel bannerImageViewModel = new BannerImageViewModel()
            {
                Id = bannerImage.Id,
                Title = bannerImage.Title,
                Discount = bannerImage.Discount,
                ImagePath = bannerImage.ImagePath
            };
            return View(bannerImageViewModel);
        }

        // POST: BannerImage/Edit/5
        [HttpPost]
        public ActionResult Edit(BannerImageViewModel bannerImageViewModel)
        {
            try
            {
                if (bannerImageViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(bannerImageViewModel.Image.FileName);
                    string extension = Path.GetExtension(bannerImageViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/BannerImage/"), fileNames);
                    bannerImageViewModel.Image.SaveAs(fileName);
                    BannerImage bannerImage = new BannerImage()
                    {
                        Id = bannerImageViewModel.Id,
                        Title = bannerImageViewModel.Title,
                        Discount = bannerImageViewModel.Discount,
                        ImagePath = path,
                    };
                    BannerImageManager.Update(bannerImage);
                }
                else
                {
                    BannerImage bannerImage = new BannerImage()
                    {
                        Id = bannerImageViewModel.Id,
                        Title = bannerImageViewModel.Title,
                        Discount = bannerImageViewModel.Discount,
                        ImagePath = bannerImageViewModel.ImagePath,
                    };
                    BannerImageManager.Update(bannerImage);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BannerImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var bannerImage = BannerImageManager.GetById((int)id);
            BannerImageViewModel bannerImageViewModel = new BannerImageViewModel()
            {
                Id = bannerImage.Id,
                Title = bannerImage.Title,
                Discount = bannerImage.Discount,
                ImagePath = bannerImage.ImagePath
            };
            var bannerImageDelete = BannerImageManager.Remove(bannerImage);
            if (bannerImageDelete)
            {
                return RedirectToAction("Index");
            }
            return View(bannerImageViewModel);
        }

        // POST: BannerImage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

DbShop/Views/BannerImages/Create.cshtml
@model DbShop.ViewModel.BannerImageViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-one widgettable">
    <div class="col-md-12 content-top-2 card">
        <div class="agileinfo-cdr">
            <div class="card-header">
                <h3>Create</h3>
                <p>
                    @Html.ActionLink("Create New Product", "Create")
                </p>
                <hr/>
            </div>
            @using (Html.BeginForm("Create", "BannerImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="file" name="Image" class="form-control"/>
                            @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Banner Title" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control", @placeholder = "Discount" } })
                            @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
</div>

DbShop/Views/BannerImages/Delete.cshtml
@model DbShop.ViewModel.BannerImageViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BannerImageViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DbShop/Views/BannerImages/Details.cshtml
@model DbShop.ViewModel.BannerImageViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-one widgettable">
    <div class="col-md-12 content-top-2 card">
        <div class="agileinfo-cdr">
            <div class="card-header">
                <h3>Banner Details</h3>
                <hr />
            </div>
            <img src="@Url.Content("~/BannerImage/" + Model.ImagePath)" style="height: 150px; width: 150px;"/><br/>
            @Html.DisplayFor(model => model.Title)<br/>
            @Html.DisplayFor(model => model.Discount)
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                @Html.ActionLink("Back to List", "Index")
            </p>

        </div>
    </div>
    <div class="clearfix"> </div>
</div>

DbShop/Views/BannerImages/Edit.cshtml
@model DbShop.ViewModel.BannerImageViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="row-one widgettable">
    <div class="col-md-12 content-top-2 card">
        <div class="agileinfo-cdr">
            <div class="card-header">
                <h3>Banner Details</h3>
                <hr />
            </div>
            @using (Html.BeginForm("Edit", "BannerImages", FormMethod.Post, new {enctype="multipart/form-data"}))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        <div class="col-md-10">
                            <img src="@Url.Content("~/BannerImage/"+ Model.ImagePath)" style="height: 100px; width: 100px;" />
                            @Html.HiddenFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                            <input type="file" name="Image" class="form-control"/>
                            @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Update" class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

        </div>
    </div>
    <div class="clearfix"> </div>
</div>

DbShop/Views/BannerImages/Index.cshtml
@model IEnumerable<DbShop.ViewModel.BannerImageViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int sl = 1;
}

<div class="row-one widgettable">
    <div class="col-md-12 content-top-2 card">
        <div class="agileinfo-cdr">
            <div class="card-header">
                <h3>Banner</h3>
                <p>
                    @Html.ActionLink("Create New Bannder", "Create")
                </p>
                <hr />
            </div>
            <table class="table table-bordered table-striped" id="myTable">
                <thead>
                <tr>
                    <th>
                        SL
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ImagePath)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Discount)
                    </th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @(sl++)
                        </td>
                        <td>
                            <img src="@Url.Content("~/BannerImage/"+ item.ImagePath)" style="width: 80px; height: 80px;" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Discount)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>