DbShop/Controllers/NewCollectionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DbShop.BLL.Contracts;
using DbShop.Models.EntityModel;
using DbShop.ViewModel;

namespace DbShop.Controllers
{
    public class NewCollectionController : Controller
    {
        // GET: NewCollection
        public INewCollectionManager NewCollectionManager;

        public NewCollectionController(INewCollectionManager Manager)
        {
            NewCollectionManager = Manager;
        }
        public ActionResult Index()
        {
            var newCollection = NewCollectionManager.GetAll();
            List<NewCollectionViewModel> newCollectionViewModels = new List<NewCollectionViewModel>();
            foreach (var item in newCollection)
            {
                newCollectionViewModels.Add(new NewCollectionViewModel()
                {
                    Id = item.Id,
                    Title = item.Title,
                    ImagePath = item.ImagePath
                });
            }
            return View(newCollectionViewModels);
        }

        // GET: NewCollection/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var newCollection = NewCollectionManager.GetById((int) id);
            NewCollectionViewModel newCollectionViewModel = new NewCollectionViewModel()
            {
                Id = newCollection.Id,
                Title = newCollection.Title,
                ImagePath = newCollection.ImagePath
            };
            return View(newCollectionViewModel);
        }

        // GET: NewCollection/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewCollection/Create
        [HttpPost]
        public ActionResult Create(NewCollectionViewModel newCollectionViewModel)
        {
            try
            {
                string fileName = Path.GetFileNameWithoutExtension(newCollectionViewModel.Image.FileName);
                string extension = Path.GetExtension(newCollectionViewModel.Image.FileName);
                var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                fileName = Path.Combine(Server.MapPath("~/NewCollectionImage/"), fileNames);
                newCollectionViewModel.Image.SaveAs(fileName);

                NewCollection newCollection = new NewCollection()
                {
                    Title = newCollectionViewModel.Title,
                    ImagePath = path
                };
                NewCollectionManager.Add(newCollection);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: NewCollection/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var newCollection = NewCollectionManager.GetById((int)id);
            NewCollectionViewModel newCollectionViewModel = new NewCollectionViewModel()
            {
                Id = newCollection.Id,
                Title = newCollection.Title,
                ImagePath = newCollection.ImagePath
            };
            return View(newCollectionViewModel);
        }

        // POST: NewCollection/Edit/5
        [HttpPost]
        public ActionResult Edit(NewCollectionViewModel newCollectionViewModel)
        {
            try
            {
                if (newCollectionViewModel.Image != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(newCollectionViewModel.Image.FileName);
                    string extension = Path.GetExtension(newCollectionViewModel.Image.FileName);
                    var fileNames = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    string path = fileName + DateTime.Now.ToString("yy-mm-dd") + extension;
                    fileName = Path.Combine(Server.MapPath("~/NewCollectionImage/"), fileNames);
                    newCollectionViewModel.Image.SaveAs(fileName);

                    NewCollection newCollection = new NewCollection()
                    {
                        Id = newCollectionViewModel.Id,
                        Title = newCollectionViewModel.Title,
                        ImagePath = path
                    };
                    NewCollectionManager.Update(newCollection);
                }
                else
                {
                    NewCollection newCollection = new NewCollection()
                    {
                        Id = newCollectionViewModel.Id,
                        Title = newCollectionViewModel.Title,
                        ImagePath = newCollectionViewModel.ImagePath
                    };
                    NewCollectionManager.Update(newCollection);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: NewCollection/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var newCollection = NewCollectionManager.GetById((int)id);
            NewCollectionManager.Remove(newCollection);
            return RedirectToAction("Index");
        }
    }
}

DbShop/Views/NewCollection/Create.cshtml
@model DbShop.ViewModel.NewCollectionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "NewCollection", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" class="form-control"/>
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DbShop/Views/NewCollection/Details.cshtml
@model DbShop.ViewModel.NewCollectionViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NewCollectionViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content("~/NewCollectionImage/"+Model.ImagePath)" style="height: 80px; width: 80px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DbShop/Views/NewCollection/Edit.cshtml
@model DbShop.ViewModel.NewCollectionViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","NewCollection", FormMethod.Post, new {enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content("~/NewCollectionImage/" + Model.ImagePath)" style="height: 80px; width: 80px;"/>
                <input type="file" class="form-control" name="Image"/>
                @Html.HiddenFor(model => model.ImagePath, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.ImagePath, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DbShop/Views/NewCollection/Index.cshtml
@model IEnumerable<DbShop.ViewModel.NewCollectionViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            <img src="@Url.Content("~/NewCollectionImage/"+item.ImagePath)" style="height: 80px; width: 80px;"/>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>